import { useEffect, useMemo, useState } from 'react'
import { ArrowLeft, ArrowRight, CarFront, Check, CheckCircle2, ClipboardCheck, FileText, LockKeyhole, Pencil, ShieldCheck, UserRound } from 'lucide-react'

type Step = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8
type YesNo = '' | 'Sim' | 'Não'
type FormData = {
  vehicleType: string; insuredName: string; insuredSex: string; contractor: string; insuredDriver: YesNo; currentInsurance: YesNo
  brand: string; model: string; version: string; manufactureYear: string; modelYear: string; zeroKm: YesNo; financed: YesNo; hasPlate: YesNo; plate: string; alarm: YesNo; antiTheft: YesNo; gasKit: YesNo; taxi: YesNo
  driverName: string; driverBirth: string; driverSex: string; maritalStatus: string; profession: string; licenseAge: string; residenceType: string; otherVehicles: YesNo; otherResidents: YesNo
  workCommute: YesNo; schoolCommute: YesNo; workUse: YesNo; professionalUse: string; monthlyKm: string; hasGarage: YesNo; garageType: string; overnightZip: string; travelZip: string
  insurer: string; policyExpiry: string; bonusClass: string; stolenLastTwoYears: YesNo; claimLastYear: YesNo
  insuredCpf: string; residentialZip: string; insuredOwner: YesNo; ownerName: string; ownerCpf: string; ownerRelation: string
  phone: string; email: string; preferredContact: string; bestTime: string
}
const initialData: FormData = { vehicleType: '', insuredName: '', insuredSex: '', contractor: '', insuredDriver: '', currentInsurance: '', brand: '', model: '', version: '', manufactureYear: '', modelYear: '', zeroKm: '', financed: '', hasPlate: '', plate: '', alarm: '', antiTheft: '', gasKit: '', taxi: '', driverName: '', driverBirth: '', driverSex: '', maritalStatus: '', profession: '', licenseAge: '', residenceType: '', otherVehicles: '', otherResidents: '', workCommute: '', schoolCommute: '', workUse: '', professionalUse: '', monthlyKm: '', hasGarage: '', garageType: '', overnightZip: '', travelZip: '', insurer: '', policyExpiry: '', bonusClass: '', stolenLastTwoYears: '', claimLastYear: '', insuredCpf: '', residentialZip: '', insuredOwner: '', ownerName: '', ownerCpf: '', ownerRelation: '', phone: '', email: '', preferredContact: '', bestTime: '' }
const stepLabels = ['Início', 'Veículo', 'Condutor', 'Utilização', 'Seguro atual', 'Segurado', 'Contato', 'Revisão']
const modelCatalog: Record<string, { model: string; versions: string[] }[]> = { Chevrolet: [{ model: 'Onix', versions: ['1.0 Turbo LT', '1.0 MT', 'Premier 1.0 Turbo'] }, { model: 'Tracker', versions: ['1.0 Turbo AT', '1.2 Turbo Premier'] }], Volkswagen: [{ model: 'T-Cross', versions: ['200 TSI', '250 TSI Comfortline'] }, { model: 'Polo', versions: ['1.0 MPI', '1.0 TSI'] }], Fiat: [{ model: 'Argo', versions: ['1.0', 'Drive 1.3'] }, { model: 'Pulse', versions: ['Drive 1.3', 'Audace 1.0 Turbo'] }] }
const yesNo = ['Sim', 'Não'] as const
const money = (value: number) => value.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' })
const onlyDigits = (value: string) => value.replace(/\D/g, '')
const maskCpf = (value: string) => onlyDigits(value).slice(0, 11).replace(/(\d{3})(\d)/, '$1.$2').replace(/(\d{3})(\d)/, '$1.$2').replace(/(\d{3})(\d{1,2})$/, '$1-$2')
const maskPhone = (value: string) => onlyDigits(value).slice(0, 11).replace(/(\d{2})(\d)/, '($1) $2').replace(/(\d{5})(\d)/, '$1-$2')
const maskZip = (value: string) => onlyDigits(value).slice(0, 8).replace(/(\d{5})(\d)/, '$1-$2')
const validCpf = (value: string) => { const cpf = onlyDigits(value); if (cpf.length !== 11 || /^([0-9])\1+$/.test(cpf)) return false; let sum = 0; for (let i = 0; i < 9; i++) sum += Number(cpf[i]) * (10 - i); let digit = (sum * 10) % 11; if (digit === 10) digit = 0; if (digit !== Number(cpf[9])) return false; sum = 0; for (let i = 0; i < 10; i++) sum += Number(cpf[i]) * (11 - i); digit = (sum * 10) % 11; return (digit === 10 ? 0 : digit) === Number(cpf[10]) }
const validPlate = (value: string) => /^[A-Z]{3}-?[0-9][A-Z0-9][0-9]{2}$/.test(value.toUpperCase())

type Props = { data: FormData; update: (field: keyof FormData, value: string) => void; errors: Record<string, string> }

function App() {
  const [step, setStep] = useState<Step>(1)
  const [data, setData] = useState<FormData>(() => { try { return { ...initialData, ...JSON.parse(localStorage.getItem('mutual-cotacao-draft') || '{}') } } catch { return initialData } })
  const [errors, setErrors] = useState<Record<string, string>>({})
  const [quote, setQuote] = useState<{ code: string; createdAt: string } | null>(null)
  const models = modelCatalog[data.brand] || []
  const currentStep = step === 5 && data.currentInsurance === 'Não' ? 6 : step
  const update = (field: keyof FormData, value: string) => setData(current => ({ ...current, [field]: value }))
  useEffect(() => { localStorage.setItem('mutual-cotacao-draft', JSON.stringify(data)) }, [data])
  useEffect(() => { if (data.insuredDriver === 'Sim' && data.driverName !== data.insuredName) setData(current => ({ ...current, driverName: current.insuredName, driverSex: current.insuredSex })) }, [data.insuredDriver, data.insuredName, data.insuredSex, data.driverName])
  useEffect(() => { if (data.insuredOwner === 'Sim' && data.ownerName !== data.insuredName) setData(current => ({ ...current, ownerName: current.insuredName, ownerCpf: current.insuredCpf })) }, [data.insuredOwner, data.insuredName, data.insuredCpf, data.ownerName])
  const premium = useMemo(() => 119 + (data.vehicleType === 'Moto' ? -38 : 0) + (data.workUse === 'Sim' ? 32 : 0) + (data.currentInsurance === 'Não' ? 14 : 0), [data])
  const validate = () => {
    const next: Record<string, string> = {}; const require = (key: keyof FormData, message: string) => { if (!data[key]) next[key] = message }
    if (currentStep === 1) { require('vehicleType', 'Selecione o tipo de veículo.'); require('insuredName', 'Informe o nome do segurado.'); require('insuredSex', 'Selecione o sexo.'); require('contractor', 'Informe quem contratará o seguro.'); require('insuredDriver', 'Responda esta pergunta.'); require('currentInsurance', 'Responda esta pergunta.') }
    if (currentStep === 2) { require('brand', 'Selecione a marca.'); require('model', 'Selecione o modelo.'); require('version', 'Selecione a versão.'); require('manufactureYear', 'Informe o ano.'); require('modelYear', 'Informe o ano do modelo.'); require('zeroKm', 'Responda esta pergunta.'); require('financed', 'Responda esta pergunta.'); require('hasPlate', 'Responda esta pergunta.'); if (data.hasPlate === 'Sim' && (!data.plate || !validPlate(data.plate))) next.plate = 'Informe uma placa válida.'; require('alarm', 'Responda esta pergunta.'); require('antiTheft', 'Responda esta pergunta.'); require('gasKit', 'Responda esta pergunta.'); require('taxi', 'Responda esta pergunta.'); if (Number(data.manufactureYear) < 1950 || Number(data.manufactureYear) > new Date().getFullYear()) next.manufactureYear = 'Ano inválido.'; if (Number(data.modelYear) < Number(data.manufactureYear)) next.modelYear = 'Não pode ser anterior ao ano de fabricação.' }
    if (currentStep === 3) { if (data.insuredDriver !== 'Sim') { require('driverName', 'Informe o nome do condutor.'); require('driverBirth', 'Informe a data de nascimento.'); require('driverSex', 'Selecione o sexo.'); require('maritalStatus', 'Selecione o estado civil.'); require('profession', 'Informe a profissão.'); require('licenseAge', 'Informe a idade.'); } require('residenceType', 'Selecione o tipo de residência.'); require('otherVehicles', 'Responda esta pergunta.'); require('otherResidents', 'Responda esta pergunta.') }
    if (currentStep === 4) { require('workCommute', 'Responda esta pergunta.'); require('schoolCommute', 'Responda esta pergunta.'); require('workUse', 'Responda esta pergunta.'); if (data.workUse === 'Sim') require('professionalUse', 'Descreva o uso profissional.'); require('monthlyKm', 'Informe a quilometragem.'); require('hasGarage', 'Responda esta pergunta.'); if (data.hasGarage === 'Sim') require('garageType', 'Selecione o tipo de garagem.'); if (data.overnightZip.length < 9) next.overnightZip = 'Informe um CEP válido.'; if (data.travelZip.length < 9) next.travelZip = 'Informe um CEP válido.' }
    if (currentStep === 5) { require('insurer', 'Informe a seguradora.'); require('policyExpiry', 'Informe o vencimento.'); require('bonusClass', 'Informe a classe de bônus.'); require('stolenLastTwoYears', 'Responda esta pergunta.'); require('claimLastYear', 'Responda esta pergunta.') }
    if (currentStep === 6) { require('insuredCpf', 'Informe o CPF.'); if (data.insuredCpf && !validCpf(data.insuredCpf)) next.insuredCpf = 'CPF inválido.'; if (data.residentialZip.length < 9) next.residentialZip = 'Informe um CEP válido.'; require('insuredOwner', 'Responda esta pergunta.'); if (data.insuredOwner === 'Não') { require('ownerName', 'Informe o proprietário.'); require('ownerCpf', 'Informe o CPF do proprietário.'); if (data.ownerCpf && !validCpf(data.ownerCpf)) next.ownerCpf = 'CPF inválido.'; require('ownerRelation', 'Informe a relação.') } }
    if (currentStep === 7) { if (onlyDigits(data.phone).length < 10) next.phone = 'Telefone inválido.'; if (!/^\S+@\S+\.\S+$/.test(data.email)) next.email = 'E-mail inválido.'; require('preferredContact', 'Escolha a forma de contato.'); require('bestTime', 'Escolha o melhor horário.') }
    setErrors(next); return Object.keys(next).length === 0
  }
  const goNext = () => { if (!validate()) return; let target = Math.min(8, currentStep + 1) as Step; if (target === 5 && data.currentInsurance === 'Não') target = 6; setStep(target) }
  const goBack = () => { let target = Math.max(1, currentStep - 1) as Step; if (target === 5 && data.currentInsurance === 'Não') target = 4; setErrors({}); setStep(target) }
  const finish = async () => {
    try {
      const response = await fetch('/api/quotes', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(data) })
      const result = await response.json()
      if (!response.ok) throw new Error(result.message || 'Não foi possível salvar a cotação.')
      setQuote({ code: result.code, createdAt: result.createdAt })
    } catch (error) {
      window.alert(error instanceof Error ? error.message : 'Não foi possível salvar a cotação.')
    }
  }
  const finishLegacy = () => { const code = `MB-${new Date().getFullYear()}-${Math.floor(100000 + Math.random() * 900000)}`; const createdAt = new Date().toISOString(); const record = { id: crypto.randomUUID(), code, status: 'Cotação recebida', createdAt, updatedAt: createdAt, origin: 'Cotação Web', insured: { name: data.insuredName, cpf: data.insuredCpf }, vehicle: { type: data.vehicleType, brand: data.brand, model: data.model, version: data.version }, driver: { name: data.driverName }, owner: { name: data.ownerName || data.insuredName }, usage: { monthlyKm: data.monthlyKm }, previousInsurance: data.currentInsurance === 'Sim' ? { insurer: data.insurer } : null, contact: { phone: data.phone, email: data.email } }; localStorage.setItem('mutual-cotacao-record', JSON.stringify(record)); setQuote({ code, createdAt }) }
  if (quote) return <main className="success-page"><div className="success-card"><img src="/images/mutual-brasil-logo.jpeg" alt="Mutual Brasil" /><div className="success-icon"><Check /></div><p className="eyebrow">Cotação enviada com sucesso</p><h1>Recebemos seus dados.</h1><p>Sua cotação foi registrada como <strong>Cotação recebida</strong>.</p><div className="success-details"><span>Número da cotação <strong>{quote.code}</strong></span><span>Segurado <strong>{data.insuredName}</strong></span><span>Veículo <strong>{data.brand} {data.model}</strong></span><span>Contato <strong>{data.phone} · {data.email}</strong></span></div><button className="button primary" onClick={() => { setQuote(null); setStep(1); setData(initialData); localStorage.removeItem('mutual-cotacao-draft') }}>Nova cotação</button></div></main>
  return <div className="app-shell"><header className="topbar"><div className="brand"><img src="/images/mutual-brasil-logo.jpeg" alt="Mutual Brasil" /><span>Proteção que pertence a todos.</span></div><div className="secure"><LockKeyhole size={16} /> Ambiente seguro</div></header><main className="layout"><aside className="intro"><p className="eyebrow">Cotação de seguro auto</p><h1>Vamos encontrar a proteção ideal.</h1><p>Uma cotação simples, transparente e feita para a sua realidade.</p><div className="intro-points"><span><ShieldCheck size={18} /> Sem burocracia</span><span><ClipboardCheck size={18} /> Você no controle</span></div><div className="aside-note"><strong>Seu progresso fica salvo</strong><span>Você pode voltar e editar qualquer etapa sem perder informações.</span></div></aside><section className="form-area"><Progress step={currentStep} currentInsurance={data.currentInsurance} />{currentStep === 1 && <Initial data={data} update={update} errors={errors} />}{currentStep === 2 && <Vehicle data={data} update={update} errors={errors} models={models} />}{currentStep === 3 && <Driver data={data} update={update} errors={errors} />}{currentStep === 4 && <Usage data={data} update={update} errors={errors} />}{currentStep === 5 && <PreviousInsurance data={data} update={update} errors={errors} />}{currentStep === 6 && <InsuredOwner data={data} update={update} errors={errors} />}{currentStep === 7 && <Contact data={data} update={update} errors={errors} />}{currentStep === 8 && <Review data={data} premium={premium} jump={setStep} />}{currentStep < 8 && <div className="actions">{currentStep > 1 && <button className="button ghost" onClick={goBack}><ArrowLeft size={18} /> Voltar</button>}<button className="button primary" onClick={goNext}>Continuar <ArrowRight size={18} /></button></div>}{currentStep === 8 && <div className="actions"><button className="button ghost" onClick={goBack}><ArrowLeft size={18} /> Voltar</button><button className="button primary" onClick={finishLegacy}>Finalizar cotação <CheckCircle2 size={18} /></button></div>}</section></main><footer>Mutual Brasil <span>•</span> Seus dados são tratados com responsabilidade.</footer></div>
}

function Progress({ step, currentInsurance }: { step: Step; currentInsurance: YesNo }) { const labels = currentInsurance === 'Sim' ? stepLabels : stepLabels.filter(label => label !== 'Seguro atual'); const displayStep = currentInsurance === 'Não' && step > 4 ? step - 1 : step; return <div className="progress"><div className="progress-track"><span style={{ width: `${(displayStep / labels.length) * 100}%` }} /></div><div className="steps">{labels.map((label, index) => <span className={displayStep >= index + 1 ? 'active' : ''} key={label}><i>{displayStep > index + 1 ? <Check size={13} /> : index + 1}</i>{label}</span>)}</div></div> }
function Heading({ number, icon, title, detail }: { number: string; icon: React.ReactNode; title: string; detail: string }) { return <div className="heading"><div className="step-number">{icon}</div><div><p className="eyebrow">Etapa {number}</p><h2>{title}</h2><p>{detail}</p></div></div> }
function Field({ label, error, children, required = true }: { label: string; error?: string; children: React.ReactNode; required?: boolean }) { return <label className="field"><span>{label}{required && <em>*</em>}</span>{children}{error && <small>{error}</small>}</label> }
function Question({ label, value, onChange, error }: { label: string; value: YesNo; onChange: (value: YesNo) => void; error?: string }) { return <div className="question"><span>{label}<em>*</em></span><div className="choice-row">{yesNo.map(option => <button type="button" className={value === option ? 'chosen' : ''} onClick={() => onChange(option)} key={option}>{option}</button>)}</div>{error && <small>{error}</small>}</div> }
function Initial({ data, update, errors }: Props) { return <div className="step-content"><Heading number="01 de 08" icon={<UserRound size={19} />} title="Vamos começar" detail="Conte o básico para iniciarmos sua cotação." /><div className="form-grid"><Field label="Tipo de veículo" error={errors.vehicleType}><select value={data.vehicleType} onChange={e => update('vehicleType', e.target.value)}><option value="">Selecione</option><option>Carro</option><option>Moto</option></select></Field><Field label="Nome do segurado" error={errors.insuredName}><input value={data.insuredName} onChange={e => update('insuredName', e.target.value)} placeholder="Nome completo" /></Field><Field label="Sexo" error={errors.insuredSex}><select value={data.insuredSex} onChange={e => update('insuredSex', e.target.value)}><option value="">Selecione</option><option>Feminino</option><option>Masculino</option><option>Prefiro não informar</option></select></Field><Field label="Quem irá contratar o seguro?" error={errors.contractor}><select value={data.contractor} onChange={e => update('contractor', e.target.value)}><option value="">Selecione</option><option>O próprio segurado</option><option>Outra pessoa</option><option>Empresa</option></select></Field></div><Question label="O segurado será o principal condutor?" value={data.insuredDriver} onChange={value => update('insuredDriver', value)} error={errors.insuredDriver} /><Question label="O veículo já possui seguro atualmente?" value={data.currentInsurance} onChange={value => update('currentInsurance', value)} error={errors.currentInsurance} /></div> }
function Vehicle({ data, update, errors, models }: Props & { models: { model: string; versions: string[] }[] }) { const versions = models.find(item => item.model === data.model)?.versions || []; return <div className="step-content"><Heading number="02 de 08" icon={<CarFront size={19} />} title="Dados do veículo" detail="Agora vamos identificar o veículo que será protegido." /><div className="form-grid"><Field label="Marca" error={errors.brand}><select value={data.brand} onChange={e => { update('brand', e.target.value); update('model', ''); update('version', '') }}><option value="">Selecione a marca</option>{Object.keys(modelCatalog).map(item => <option key={item}>{item}</option>)}</select></Field><Field label="Modelo" error={errors.model}><select value={data.model} onChange={e => { update('model', e.target.value); update('version', '') }} disabled={!data.brand}><option value="">Selecione o modelo</option>{models.map(item => <option key={item.model}>{item.model}</option>)}</select></Field><Field label="Versão" error={errors.version}><select value={data.version} onChange={e => update('version', e.target.value)} disabled={!data.model}><option value="">Selecione a versão</option>{versions.map(item => <option key={item}>{item}</option>)}</select></Field><Field label="Ano de fabricação" error={errors.manufactureYear}><input inputMode="numeric" value={data.manufactureYear} onChange={e => update('manufactureYear', e.target.value.replace(/\D/g, '').slice(0, 4))} placeholder="2022" /></Field><Field label="Ano do modelo" error={errors.modelYear}><input inputMode="numeric" value={data.modelYear} onChange={e => update('modelYear', e.target.value.replace(/\D/g, '').slice(0, 4))} placeholder="2023" /></Field></div><Question label="O veículo é 0 km?" value={data.zeroKm} onChange={value => update('zeroKm', value)} error={errors.zeroKm} /><Question label="O veículo é financiado ou alienado?" value={data.financed} onChange={value => update('financed', value)} error={errors.financed} /><Question label="O veículo possui placa?" value={data.hasPlate} onChange={value => update('hasPlate', value)} error={errors.hasPlate} />{data.hasPlate === 'Sim' && <Field label="Placa" error={errors.plate}><input value={data.plate} onChange={e => update('plate', e.target.value.toUpperCase().replace(/[^A-Z0-9-]/g, '').slice(0, 8))} placeholder="ABC-1D23 ou ABC-1234" /></Field>}<div className="question-grid"><Question label="Possui alarme?" value={data.alarm} onChange={value => update('alarm', value)} error={errors.alarm} /><Question label="Possui dispositivo antifurto?" value={data.antiTheft} onChange={value => update('antiTheft', value)} error={errors.antiTheft} /><Question label="Possui kit gás?" value={data.gasKit} onChange={value => update('gasKit', value)} error={errors.gasKit} /><Question label="É táxi?" value={data.taxi} onChange={value => update('taxi', value)} error={errors.taxi} /></div></div> }
function Driver({ data, update, errors }: Props) { const reuse = data.insuredDriver === 'Sim'; return <div className="step-content"><Heading number="03 de 08" icon={<UserRound size={19} />} title="Quem dirige o veículo?" detail={reuse ? 'Reaproveitamos os dados do segurado como principal condutor.' : 'Precisamos conhecer o principal condutor.'} /><div className="form-grid"><Field label="Nome completo do principal condutor" error={errors.driverName}><input disabled={reuse} value={reuse ? data.insuredName : data.driverName} onChange={e => update('driverName', e.target.value)} placeholder="Nome completo" /></Field><Field label="Data de nascimento" error={errors.driverBirth}><input type="date" value={data.driverBirth} onChange={e => update('driverBirth', e.target.value)} max={new Date().toISOString().slice(0, 10)} /></Field><Field label="Sexo" error={errors.driverSex}><select disabled={reuse} value={reuse ? data.insuredSex : data.driverSex} onChange={e => update('driverSex', e.target.value)}><option value="">Selecione</option><option>Feminino</option><option>Masculino</option><option>Prefiro não informar</option></select></Field><Field label="Estado civil" error={errors.maritalStatus}><select value={data.maritalStatus} onChange={e => update('maritalStatus', e.target.value)}><option value="">Selecione</option><option>Solteiro(a)</option><option>Casado(a)</option><option>Divorciado(a)</option><option>Viúvo(a)</option></select></Field><Field label="Profissão" error={errors.profession}><input value={data.profession} onChange={e => update('profession', e.target.value)} placeholder="Sua profissão" /></Field><Field label="Com quantos anos tirou a habilitação?" error={errors.licenseAge}><input inputMode="numeric" value={data.licenseAge} onChange={e => update('licenseAge', e.target.value.replace(/\D/g, '').slice(0, 2))} placeholder="Ex.: 18" /></Field><Field label="Tipo de residência" error={errors.residenceType}><select value={data.residenceType} onChange={e => update('residenceType', e.target.value)}><option value="">Selecione</option><option>Casa</option><option>Apartamento</option><option>Sobrado</option><option>Outros</option></select></Field></div><Question label="Existem outros veículos na residência?" value={data.otherVehicles} onChange={value => update('otherVehicles', value)} error={errors.otherVehicles} /><Question label="Existem outros moradores, dependentes ou condutores com 17 anos ou mais?" value={data.otherResidents} onChange={value => update('otherResidents', value)} error={errors.otherResidents} /></div> }
function Usage({ data, update, errors }: Props) { return <div className="step-content"><Heading number="04 de 08" icon={<CarFront size={19} />} title="Como o veículo é utilizado?" detail="Essas respostas ajudam a entender sua rotina." /><Question label="Utiliza o veículo para ir ao trabalho?" value={data.workCommute} onChange={value => update('workCommute', value)} error={errors.workCommute} /><Question label="Utiliza para ir à escola ou faculdade?" value={data.schoolCommute} onChange={value => update('schoolCommute', value)} error={errors.schoolCommute} /><Question label="Utiliza o veículo durante o trabalho?" value={data.workUse} onChange={value => update('workUse', value)} error={errors.workUse} />{data.workUse === 'Sim' && <Field label="Descreva o uso profissional" error={errors.professionalUse}><textarea value={data.professionalUse} onChange={e => update('professionalUse', e.target.value)} placeholder="Ex.: visitas a clientes, entregas..." rows={3} /></Field>}<div className="form-grid"><Field label="Quilometragem média mensal" error={errors.monthlyKm}><input inputMode="numeric" value={data.monthlyKm} onChange={e => update('monthlyKm', e.target.value.replace(/\D/g, ''))} placeholder="Ex.: 1.500 km" /></Field><Question label="O veículo possui garagem durante a noite?" value={data.hasGarage} onChange={value => update('hasGarage', value)} error={errors.hasGarage} />{data.hasGarage === 'Sim' && <Field label="Tipo de garagem" error={errors.garageType}><select value={data.garageType} onChange={e => update('garageType', e.target.value)}><option value="">Selecione</option><option>Particular fechada</option><option>Particular aberta</option><option>Condomínio</option><option>Estacionamento</option></select></Field>}<Field label="CEP de pernoite" error={errors.overnightZip}><input inputMode="numeric" value={data.overnightZip} onChange={e => update('overnightZip', maskZip(e.target.value))} placeholder="00000-000" /></Field><Field label="CEP da região para onde mais se desloca" error={errors.travelZip}><input inputMode="numeric" value={data.travelZip} onChange={e => update('travelZip', maskZip(e.target.value))} placeholder="00000-000" /></Field></div></div> }
function PreviousInsurance({ data, update, errors }: Props) { return <div className="step-content"><Heading number="05 de 08" icon={<ShieldCheck size={19} />} title="Seguro atual" detail="Vamos entender seu histórico para considerar as melhores condições." /><div className="form-grid"><Field label="Seguradora atual" error={errors.insurer}><input value={data.insurer} onChange={e => update('insurer', e.target.value)} placeholder="Nome da seguradora" /></Field><Field label="Data de vencimento da apólice" error={errors.policyExpiry}><input type="date" value={data.policyExpiry} onChange={e => update('policyExpiry', e.target.value)} /></Field><Field label="Classe de bônus" error={errors.bonusClass}><select value={data.bonusClass} onChange={e => update('bonusClass', e.target.value)}><option value="">Selecione</option>{Array.from({ length: 11 }, (_, index) => <option key={index}>{index}</option>)}</select></Field></div><Question label="O veículo foi roubado nos últimos 2 anos?" value={data.stolenLastTwoYears} onChange={value => update('stolenLastTwoYears', value)} error={errors.stolenLastTwoYears} /><Question label="Houve colisão ou sinistro no último ano?" value={data.claimLastYear} onChange={value => update('claimLastYear', value)} error={errors.claimLastYear} /></div> }
function InsuredOwner({ data, update, errors }: Props) { return <div className="step-content"><Heading number="06 de 08" icon={<FileText size={19} />} title="Dados do segurado" detail="Segurado, condutor e proprietário podem ser pessoas diferentes." /><div className="form-grid"><Field label="Nome completo"><input value={data.insuredName} disabled /></Field><Field label="CPF" error={errors.insuredCpf}><input value={data.insuredCpf} onChange={e => update('insuredCpf', maskCpf(e.target.value))} placeholder="000.000.000-00" inputMode="numeric" /></Field><Field label="CEP residencial" error={errors.residentialZip}><input value={data.residentialZip} onChange={e => update('residentialZip', maskZip(e.target.value))} placeholder="00000-000" inputMode="numeric" /></Field></div><Question label="O segurado é o proprietário do veículo?" value={data.insuredOwner} onChange={value => update('insuredOwner', value)} error={errors.insuredOwner} />{data.insuredOwner === 'Não' && <div className="form-grid"><Field label="Nome completo do proprietário" error={errors.ownerName}><input value={data.ownerName} onChange={e => update('ownerName', e.target.value)} placeholder="Nome completo" /></Field><Field label="CPF do proprietário" error={errors.ownerCpf}><input value={data.ownerCpf} onChange={e => update('ownerCpf', maskCpf(e.target.value))} placeholder="000.000.000-00" /></Field><Field label="Relação com o segurado" error={errors.ownerRelation}><select value={data.ownerRelation} onChange={e => update('ownerRelation', e.target.value)}><option value="">Selecione</option><option>Cônjuge</option><option>Familiar</option><option>Empresa</option><option>Outra</option></select></Field></div>}{data.insuredOwner === 'Sim' && <div className="info-box"><CheckCircle2 size={19} /> O proprietário será registrado com os mesmos dados do segurado.</div>}</div> }
function Contact({ data, update, errors }: Props) { return <div className="step-content"><Heading number="07 de 08" icon={<ClipboardCheck size={19} />} title="Como podemos entrar em contato?" detail="Usaremos estes dados somente para dar continuidade à sua cotação." /><div className="form-grid"><Field label="Telefone" error={errors.phone}><input value={data.phone} onChange={e => update('phone', maskPhone(e.target.value))} placeholder="(00) 00000-0000" inputMode="tel" /></Field><Field label="E-mail" error={errors.email}><input type="email" value={data.email} onChange={e => update('email', e.target.value)} placeholder="voce@email.com" /></Field><Field label="Forma preferencial de contato" error={errors.preferredContact}><select value={data.preferredContact} onChange={e => update('preferredContact', e.target.value)}><option value="">Selecione</option><option>Telefone</option><option>WhatsApp</option><option>E-mail</option></select></Field><Field label="Melhor horário para contato" error={errors.bestTime}><select value={data.bestTime} onChange={e => update('bestTime', e.target.value)}><option value="">Selecione</option><option>Manhã</option><option>Tarde</option><option>Noite</option><option>Qualquer horário</option></select></Field></div></div> }
function Review({ data, premium, jump }: { data: FormData; premium: number; jump: (step: Step) => void }) { const blocks = [{ title: 'Dados do veículo', value: `${data.brand} ${data.model} ${data.version} · ${data.modelYear}`, step: 2 as Step }, { title: 'Segurado', value: `${data.insuredName} · CPF ${data.insuredCpf}`, step: 6 as Step }, { title: 'Principal condutor', value: `${data.driverName} · ${data.profession}`, step: 3 as Step }, { title: 'Utilização', value: `${data.monthlyKm} km/mês · Pernoite ${data.overnightZip}`, step: 4 as Step }, ...(data.currentInsurance === 'Sim' ? [{ title: 'Seguro atual', value: `${data.insurer} · Bônus ${data.bonusClass}`, step: 5 as Step }] : []), { title: 'Proprietário', value: data.insuredOwner === 'Sim' ? 'O próprio segurado' : `${data.ownerName} · ${data.ownerRelation}`, step: 6 as Step }, { title: 'Contato', value: `${data.phone} · ${data.email}`, step: 7 as Step }]; return <div className="step-content"><Heading number="08 de 08" icon={<FileText size={19} />} title="Revise sua cotação" detail="Confira os dados e edite qualquer bloco antes de finalizar." /><div className="review-list">{blocks.map(block => <div className="review-block" key={block.title}><div><span>{block.title}</span><strong>{block.value}</strong></div><button type="button" onClick={() => jump(block.step)}><Pencil size={14} /> Editar</button></div>)}</div><div className="estimate"><span>Estimativa de contribuição mensal</span><strong>{money(premium)} <small>/ mês</small></strong></div></div> }

export default App
